### PR TITLE
Use JSON5 to parse babelrc

### PR DESCRIPTION
**Pull request by STRML**
Also made write-json-file dep explicit

### CODE REVIEW

**Comment by hzoo** [comment]
Awesome, nice work!

**Comment by hzoo** [comment]
Although dang I realize the comments are removed now.. hmm

**Comment by STRML** [comment]
No way around that, unless we parse the cst of the whole thing afaik.

**Comment by hzoo** [comment]
Don't think it's that necessary to fix though, just realized it

**Comment by STRML** [comment]
Yeah I agree. Wish we could and maybe we should note it, but that's about
all.

**Comment by hzoo** [comment]
Yeah having a caveat for that is good.

Or we just append `var a = ` to parse as js, codemod that and write it as js without `var a =` lol

**Comment by STRML** [comment]
That's insane, I love it, we should do it.

**Comment by lzhuor** [comment]
Nice work!

------------------

It might not be a good practice to post this message here, please feel free to remove it:

@STRML Such a small world! I forked your home page about 3 years ago, I love it! World Peace!

**Pull request merged**
