### PR TITLE
Verifies that the installed dependency is less than expected

### LINKED ISSUE #66: babel-upgrade downgraded babel-loader
Hi,

I had babel-loader version higher than babel-uprade suggested me, here is what happened:

```
-  "babel-loader": "^8.0.0-beta.3",
+  "babel-loader": "^8.0.0-beta.0",
```

### PR DESCRIPTION
**Pull request by emersonlaurentino**
closes #66

### CODE REVIEW

**Comment by suchipi** [comment]
Could you add a test?

**Comment by emersonlaurentino** [comment]
@suchipi Yes, of course.

**Comment by emersonlaurentino** [comment]
hey @suchipi, I'm having the following problem:

_ps.: this persists in `master`_

```js
  ● writes when --write is passed

    expect(jest.fn()).toBeCalled()
    
    Expected mock function to have been called.

      27 | 
      28 |   await writePackageJSON({ write: true });
    > 29 |   expect(writeJsonFile).toBeCalled();
      30 |   writeJsonFile.mockReset();
      31 | 
      32 |   await writeBabelRC("./fixtures/babelrc.json5", { write: true });

```

Do you have any idea how to solve it?

**Comment by emersonlaurentino** [comment]
I was having an unusual problem, when I installed the dependencies with npm and tried to run the test with yarn, it removed all my dependencies from the package.json

**Comment by emersonlaurentino** [comment]
done @suchipi

**Comment by hzoo** [comment]
nice work!

**Pull request merged**
