### PR TITLE
Ignore all node_modules

### LINKED ISSUE #27: Globby finds files in lerna packages node_modules
In a lerna monorepo the root's `node_modules` will be ignored but not `node_modules` from the packages. Is this intended behavior?

I am using my babel6 test repo https://github.com/Raigen/babel6-tmp
```js
globby(['**/.babelrc', '!./node_modules/**'])

[ 'packages/pck1/.babelrc',
  'packages/pck1/node_modules/pck2/.babelrc',
  'packages/pck2/.babelrc' ]
```
With this pattern it works as I would expect it.
```js
globby(['**/.babelrc', '!**/node_modules/**'])

[ 'packages/pck1/.babelrc', 'packages/pck2/.babelrc' ]
```

Especially for the `package.json` this becomes a long list when dependencies are already installed via `lerna bootstrap` when I run `npx babel-upgrade` in the repo.
This does also caused me problems in our main project. I had a `dist` directory with copied `node_modules` still lying around and that was why `babel-upgrade` did not updated the `.babelrc`, because it found a lot of `package.json` and it does not update `.babelrc` when more than one `package.json` is found.

### PR DESCRIPTION
**Pull request by Raigen**
Ignore all occurrences of node_modules in possible subdirectories.

Fixes #27

### CODE REVIEW

**Comment by existentialism** [comment]
@Raigen Thanks for the PR! Can you also change: https://github.com/babel/babel-upgrade/blob/master/src/index.js#L58?

**Comment by Raigen** [comment]
@existentialism Done!

**Comment by hzoo** [comment]
lol I don't know how to use globs I guess? 

I am curious about this option though https://github.com/sindresorhus/globby#gitignore - would turning this on be the same affect? does anyone want to test that?

**Comment by hzoo** [comment]
and we should figure out a test for this

**Pull request merged**
